services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: onboarding_db
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
        context: .
        dockerfile: ./Onboarding/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: onboarding_db
volumes:
  mysql-data:
